databases:
  - name: authenticate-me
    user: authenticate-me
    plan: free
    region: oregon

services:
  - type: web
    name: authenticate-me
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: authenticate-me
          property: connectionString
      - key: 48db612a49e4c855412c5a653decffad
        sync: false