databases:
  - name: ekin
    user: authenticate-me
    plan: free
    region: oregon

services:
  - type: web
    name: ekin
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: authenticate-me
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false